init:
  - git config --global core.autocrlf true

version: '{branch}-{build}'

image: Visual Studio 2017

skip_tags: true

configuration: Release
platform: Any CPU

shallow_clone: false

environment:
  COVERALLS_REPO_TOKEN:
    secure: 4bjcxJAlpTuD+dzkCq0F2tP+41+Cfx7lwxEi1ivUFkSKwq5py9DBXKdCXwqpR+zK

before_build:
- cmd: >-
    git submodule update --init --recursive
    
    _build\version.bat
    
    _build\restore.bat PoorMansTSqlFormatterRedux
    
build_script:
- cmd: _build\build.bat PoorMansTSqlFormatterRedux

test_script:
- cmd: _build\test.bat PoorMansTSqlFormatterRedux netcoreapp1.1

after_test:
- cmd: _build\package.bat PoorMansTSqlFormatterRedux

artifacts:
- path: '*.nupkg'
  name: Nuget Package

deploy:
- provider: NuGet
  api_key:
    secure: P2oh37pn3l7Tp9qTP87aOB0GFxg8WnlFyV8n3p1eqMS5aUVur1Yg3xQ2inbIDOCr
  skip_symbols: false
  on:
    branch: master